//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.ColorPalette;

namespace zenonExtensions
{
  public static class ColorPaletteCollection
  {
    public static void SetColorNames(this IColorPaletteCollection colorPaletteCollection, string colorNames)
    {
      colorPaletteCollection.SetDynamicProperty("ColorNames",colorNames);
    }

    public static string GetColorNames(this IColorPaletteCollection colorPaletteCollection)
    {
    return (string) colorPaletteCollection.GetDynamicProperty("ColorNames");
    }

    public static void SetPalette(this IColorPaletteCollection colorPaletteCollection, object palette)
    {
      colorPaletteCollection.SetDynamicProperty("Palette",palette);
    }

    public static object GetPalette(this IColorPaletteCollection colorPaletteCollection)
    {
    return (object) colorPaletteCollection.GetDynamicProperty("Palette");
    }

    public static void SetPaletteName(this IColorPaletteCollection colorPaletteCollection, string paletteName)
    {
      colorPaletteCollection.SetDynamicProperty("PaletteName",paletteName);
    }

    public static string GetPaletteName(this IColorPaletteCollection colorPaletteCollection)
    {
    return (string) colorPaletteCollection.GetDynamicProperty("PaletteName");
    }

    public static void SetPaletteColors(this IColorPaletteCollection colorPaletteCollection, string paletteColors)
    {
      colorPaletteCollection.SetDynamicProperty("PaletteColors",paletteColors);
    }

    public static string GetPaletteColors(this IColorPaletteCollection colorPaletteCollection)
    {
    return (string) colorPaletteCollection.GetDynamicProperty("PaletteColors");
    }

  }
}
