//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.FontList;

namespace zenonExtensions
{
  public static class Font
  {
    public static void SetGRP_General(this IFont font, object gRP_General)
    {
      font.SetDynamicProperty("GRP_General",gRP_General);
    }

    public static object GetGRP_General(this IFont font)
    {
    return (object) font.GetDynamicProperty("GRP_General");
    }

    public static void SetName(this IFont font, string name)
    {
      font.SetDynamicProperty("Name",name);
    }

    public static string GetName(this IFont font)
    {
    return (string) font.GetDynamicProperty("Name");
    }

    public static void SetFont(this IFont font, string z_font)
    {
      font.SetDynamicProperty("Font",z_font);
    }

    public static string GetFont(this IFont font)
    {
    return (string) font.GetDynamicProperty("Font");
    }

    public static void SetNumber(this IFont font, ushort number)
    {
      font.SetDynamicProperty("Number",number);
    }

    public static ushort GetNumber(this IFont font)
    {
    return (ushort) font.GetDynamicProperty("Number");
    }

  }
}
