//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.Function;

namespace zenonExtensions
{
  public static class Script
  {
    public static void SetGRP_General(this IScript script, object gRP_General)
    {
      script.SetDynamicProperty("GRP_General",gRP_General);
    }

    public static object GetGRP_General(this IScript script)
    {
    return (object) script.GetDynamicProperty("GRP_General");
    }

    public static void SetDeleteScript(this IScript script, string deleteScript)
    {
      script.SetDynamicProperty("DeleteScript",deleteScript);
    }

    public static string GetDeleteScript(this IScript script)
    {
    return (string) script.GetDynamicProperty("DeleteScript");
    }

    public static void SetSystemModelGroup(this IScript script, object systemModelGroup)
    {
      script.SetDynamicProperty("SystemModelGroup",systemModelGroup);
    }

    public static object GetSystemModelGroup(this IScript script)
    {
    return (object) script.GetDynamicProperty("SystemModelGroup");
    }

    public static void SetFunctions(this IScript script, string functions)
    {
      script.SetDynamicProperty("Functions",functions);
    }

    public static string GetFunctions(this IScript script)
    {
    return (string) script.GetDynamicProperty("Functions");
    }

  }
}
