//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.Menu;

namespace zenonExtensions
{
  public static class MenuItem
  {
    public static void SetGRP_Represantation(this IMenuItem menuItem, object gRP_Represantation)
    {
      menuItem.SetDynamicProperty("GRP_Represantation",gRP_Represantation);
    }

    public static object GetGRP_Represantation(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("GRP_Represantation");
    }

    public static void SetGRP_BackgroundPicture(this IMenuItem menuItem, object gRP_BackgroundPicture)
    {
      menuItem.SetDynamicProperty("GRP_BackgroundPicture",gRP_BackgroundPicture);
    }

    public static object GetGRP_BackgroundPicture(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("GRP_BackgroundPicture");
    }

    public static void SetGRP_Separator(this IMenuItem menuItem, object gRP_Separator)
    {
      menuItem.SetDynamicProperty("GRP_Separator",gRP_Separator);
    }

    public static object GetGRP_Separator(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("GRP_Separator");
    }

    public static void SetGRP_Rights(this IMenuItem menuItem, object gRP_Rights)
    {
      menuItem.SetDynamicProperty("GRP_Rights",gRP_Rights);
    }

    public static object GetGRP_Rights(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("GRP_Rights");
    }

    public static void SetGRP_SetValue(this IMenuItem menuItem, object gRP_SetValue)
    {
      menuItem.SetDynamicProperty("GRP_SetValue",gRP_SetValue);
    }

    public static object GetGRP_SetValue(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("GRP_SetValue");
    }

    public static void SetGRP_Function(this IMenuItem menuItem, object gRP_Function)
    {
      menuItem.SetDynamicProperty("GRP_Function",gRP_Function);
    }

    public static object GetGRP_Function(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("GRP_Function");
    }

    public static void SetGRP_Help(this IMenuItem menuItem, object gRP_Help)
    {
      menuItem.SetDynamicProperty("GRP_Help",gRP_Help);
    }

    public static object GetGRP_Help(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("GRP_Help");
    }

    public static void SetGRP_ExtendedTrend(this IMenuItem menuItem, object gRP_ExtendedTrend)
    {
      menuItem.SetDynamicProperty("GRP_ExtendedTrend",gRP_ExtendedTrend);
    }

    public static object GetGRP_ExtendedTrend(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("GRP_ExtendedTrend");
    }

    public static void SetLocking(this IMenuItem menuItem, uint locking)
    {
      menuItem.SetDynamicProperty("Locking",locking);
    }

    public static uint GetLocking(this IMenuItem menuItem)
    {
    return (uint) menuItem.GetDynamicProperty("Locking");
    }

    public static void SetSignature(this IMenuItem menuItem, bool signature)
    {
      menuItem.SetDynamicProperty("Signature",signature);
    }

    public static bool GetSignature(this IMenuItem menuItem)
    {
    return (bool) menuItem.GetDynamicProperty("Signature");
    }

    public static void SetSignatureMode(this IMenuItem menuItem, ushort signatureMode)
    {
      menuItem.SetDynamicProperty("SignatureMode",signatureMode);
    }

    public static ushort GetSignatureMode(this IMenuItem menuItem)
    {
    return (ushort) menuItem.GetDynamicProperty("SignatureMode");
    }

    public static void SetSignatureText(this IMenuItem menuItem, string signatureText)
    {
      menuItem.SetDynamicProperty("SignatureText",signatureText);
    }

    public static string GetSignatureText(this IMenuItem menuItem)
    {
    return (string) menuItem.GetDynamicProperty("SignatureText");
    }

    public static void SetSignatureEditModus(this IMenuItem menuItem, short signatureEditModus)
    {
      menuItem.SetDynamicProperty("SignatureEditModus",signatureEditModus);
    }

    public static short GetSignatureEditModus(this IMenuItem menuItem)
    {
    return (short) menuItem.GetDynamicProperty("SignatureEditModus");
    }

    public static void SetPopup_Menu(this IMenuItem menuItem, bool popup_Menu)
    {
      menuItem.SetDynamicProperty("Popup_Menu",popup_Menu);
    }

    public static bool GetPopup_Menu(this IMenuItem menuItem)
    {
    return (bool) menuItem.GetDynamicProperty("Popup_Menu");
    }

    public static void SetSeparatorWidth(this IMenuItem menuItem, byte separatorWidth)
    {
      menuItem.SetDynamicProperty("SeparatorWidth",separatorWidth);
    }

    public static byte GetSeparatorWidth(this IMenuItem menuItem)
    {
    return (byte) menuItem.GetDynamicProperty("SeparatorWidth");
    }

    public static void SetSeparatorColor(this IMenuItem menuItem, uint separatorColor)
    {
      menuItem.SetDynamicProperty("SeparatorColor",separatorColor);
    }

    public static uint GetSeparatorColor(this IMenuItem menuItem)
    {
    return (uint) menuItem.GetDynamicProperty("SeparatorColor");
    }

    public static void SetBackgroundPicture(this IMenuItem menuItem, string backgroundPicture)
    {
      menuItem.SetDynamicProperty("BackgroundPicture",backgroundPicture);
    }

    public static string GetBackgroundPicture(this IMenuItem menuItem)
    {
    return (string) menuItem.GetDynamicProperty("BackgroundPicture");
    }

    public static void SetBackgroundPicRepres(this IMenuItem menuItem, short backgroundPicRepres)
    {
      menuItem.SetDynamicProperty("BackgroundPicRepres",backgroundPicRepres);
    }

    public static short GetBackgroundPicRepres(this IMenuItem menuItem)
    {
    return (short) menuItem.GetDynamicProperty("BackgroundPicRepres");
    }

    public static void SetHelpCapture(this IMenuItem menuItem, string helpCapture)
    {
      menuItem.SetDynamicProperty("HelpCapture",helpCapture);
    }

    public static string GetHelpCapture(this IMenuItem menuItem)
    {
    return (string) menuItem.GetDynamicProperty("HelpCapture");
    }

    public static void SetFunction(this IMenuItem menuItem, object function)
    {
      menuItem.SetDynamicProperty("Function",function);
    }

    public static object GetFunction(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("Function");
    }

    public static void SetVBA_Macro(this IMenuItem menuItem, uint vBA_Macro)
    {
      menuItem.SetDynamicProperty("VBA_Macro",vBA_Macro);
    }

    public static uint GetVBA_Macro(this IMenuItem menuItem)
    {
    return (uint) menuItem.GetDynamicProperty("VBA_Macro");
    }

    public static void SetFromElem(this IMenuItem menuItem, bool fromElem)
    {
      menuItem.SetDynamicProperty("FromElem",fromElem);
    }

    public static bool GetFromElem(this IMenuItem menuItem)
    {
    return (bool) menuItem.GetDynamicProperty("FromElem");
    }

    public static void SetVariable(this IMenuItem menuItem, object variable)
    {
      menuItem.SetDynamicProperty("Variable",variable);
    }

    public static object GetVariable(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("Variable");
    }

    public static void SetSWDialog(this IMenuItem menuItem, bool sWDialog)
    {
      menuItem.SetDynamicProperty("SWDialog",sWDialog);
    }

    public static bool GetSWDialog(this IMenuItem menuItem)
    {
    return (bool) menuItem.GetDynamicProperty("SWDialog");
    }

    public static void SetActValue(this IMenuItem menuItem, bool actValue)
    {
      menuItem.SetDynamicProperty("ActValue",actValue);
    }

    public static bool GetActValue(this IMenuItem menuItem)
    {
    return (bool) menuItem.GetDynamicProperty("ActValue");
    }

    public static void SetSollwert(this IMenuItem menuItem, double sollwert)
    {
      menuItem.SetDynamicProperty("Sollwert",sollwert);
    }

    public static double GetSollwert(this IMenuItem menuItem)
    {
    return (double) menuItem.GetDynamicProperty("Sollwert");
    }

    public static void SetScreen(this IMenuItem menuItem, string screen)
    {
      menuItem.SetDynamicProperty("Screen",screen);
    }

    public static string GetScreen(this IMenuItem menuItem)
    {
    return (string) menuItem.GetDynamicProperty("Screen");
    }

    public static void SetRelativeTimeFilter(this IMenuItem menuItem, string relativeTimeFilter)
    {
      menuItem.SetDynamicProperty("RelativeTimeFilter",relativeTimeFilter);
    }

    public static string GetRelativeTimeFilter(this IMenuItem menuItem)
    {
    return (string) menuItem.GetDynamicProperty("RelativeTimeFilter");
    }

    public static void SetRefreshrate(this IMenuItem menuItem, float refreshrate)
    {
      menuItem.SetDynamicProperty("Refreshrate",refreshrate);
    }

    public static float GetRefreshrate(this IMenuItem menuItem)
    {
    return (float) menuItem.GetDynamicProperty("Refreshrate");
    }

    public static void SetDiagramStyle(this IMenuItem menuItem, System.Guid diagramStyle)
    {
      menuItem.SetDynamicProperty("DiagramStyle",diagramStyle);
    }

    public static System.Guid GetDiagramStyle(this IMenuItem menuItem)
    {
    return (System.Guid) menuItem.GetDynamicProperty("DiagramStyle");
    }

    public static void SetKeyData1(this IMenuItem menuItem, uint keyData1)
    {
      menuItem.SetDynamicProperty("KeyData1",keyData1);
    }

    public static uint GetKeyData1(this IMenuItem menuItem)
    {
    return (uint) menuItem.GetDynamicProperty("KeyData1");
    }

    public static void SetKeyData2(this IMenuItem menuItem, uint keyData2)
    {
      menuItem.SetDynamicProperty("KeyData2",keyData2);
    }

    public static uint GetKeyData2(this IMenuItem menuItem)
    {
    return (uint) menuItem.GetDynamicProperty("KeyData2");
    }

    public static void SetPropZenMenuItemBase(this IMenuItem menuItem, object propZenMenuItemBase)
    {
      menuItem.SetDynamicProperty("PropZenMenuItemBase",propZenMenuItemBase);
    }

    public static object GetPropZenMenuItemBase(this IMenuItem menuItem)
    {
    return (object) menuItem.GetDynamicProperty("PropZenMenuItemBase");
    }

  }
}
