//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.Recipe;

namespace zenonExtensions
{
  public static class StandardRecipeValue
  {
    public static void SetVarName(this IStandardRecipeValue standardRecipeValue, string varName)
    {
      standardRecipeValue.SetDynamicProperty("VarName",varName);
    }

    public static string GetVarName(this IStandardRecipeValue standardRecipeValue)
    {
    return (string) standardRecipeValue.GetDynamicProperty("VarName");
    }

    public static void SetVarTagName(this IStandardRecipeValue standardRecipeValue, string varTagName)
    {
      standardRecipeValue.SetDynamicProperty("VarTagName",varTagName);
    }

    public static string GetVarTagName(this IStandardRecipeValue standardRecipeValue)
    {
    return (string) standardRecipeValue.GetDynamicProperty("VarTagName");
    }

    public static void SetVarUnit(this IStandardRecipeValue standardRecipeValue, string varUnit)
    {
      standardRecipeValue.SetDynamicProperty("VarUnit",varUnit);
    }

    public static string GetVarUnit(this IStandardRecipeValue standardRecipeValue)
    {
    return (string) standardRecipeValue.GetDynamicProperty("VarUnit");
    }

    public static void SetMinimum(this IStandardRecipeValue standardRecipeValue, double minimum)
    {
      standardRecipeValue.SetDynamicProperty("Minimum",minimum);
    }

    public static double GetMinimum(this IStandardRecipeValue standardRecipeValue)
    {
    return (double) standardRecipeValue.GetDynamicProperty("Minimum");
    }

    public static void SetSetValue(this IStandardRecipeValue standardRecipeValue, double setValue)
    {
      standardRecipeValue.SetDynamicProperty("SetValue",setValue);
    }

    public static double GetSetValue(this IStandardRecipeValue standardRecipeValue)
    {
    return (double) standardRecipeValue.GetDynamicProperty("SetValue");
    }

    public static void SetMaximum(this IStandardRecipeValue standardRecipeValue, double maximum)
    {
      standardRecipeValue.SetDynamicProperty("Maximum",maximum);
    }

    public static double GetMaximum(this IStandardRecipeValue standardRecipeValue)
    {
    return (double) standardRecipeValue.GetDynamicProperty("Maximum");
    }

    public static void SetRecipeVar(this IStandardRecipeValue standardRecipeValue, object recipeVar)
    {
      standardRecipeValue.SetDynamicProperty("RecipeVar",recipeVar);
    }

    public static object GetRecipeVar(this IStandardRecipeValue standardRecipeValue)
    {
    return (object) standardRecipeValue.GetDynamicProperty("RecipeVar");
    }

    public static void SetOrderID(this IStandardRecipeValue standardRecipeValue, int orderID)
    {
      standardRecipeValue.SetDynamicProperty("OrderID",orderID);
    }

    public static int GetOrderID(this IStandardRecipeValue standardRecipeValue)
    {
    return (int) standardRecipeValue.GetDynamicProperty("OrderID");
    }

  }
}
