//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.ScreenElement;

namespace zenonExtensions
{
  public static class ControlElement
  {
    public static void SetMenuID(this IControlElement controlElement, uint menuID)
    {
      controlElement.SetDynamicProperty("MenuID",menuID);
    }

    public static uint GetMenuID(this IControlElement controlElement)
    {
    return (uint) controlElement.GetDynamicProperty("MenuID");
    }

    public static void SetDefault(this IControlElement controlElement, bool z_default)
    {
      controlElement.SetDynamicProperty("Default",z_default);
    }

    public static bool GetDefault(this IControlElement controlElement)
    {
    return (bool) controlElement.GetDynamicProperty("Default");
    }

    public static void SetText(this IControlElement controlElement, string text)
    {
      controlElement.SetDynamicProperty("Text",text);
    }

    public static string GetText(this IControlElement controlElement)
    {
    return (string) controlElement.GetDynamicProperty("Text");
    }

    public static void SetStyle(this IControlElement controlElement, uint style)
    {
      controlElement.SetDynamicProperty("Style",style);
    }

    public static uint GetStyle(this IControlElement controlElement)
    {
    return (uint) controlElement.GetDynamicProperty("Style");
    }

    public static void SetStyleMask(this IControlElement controlElement, uint styleMask)
    {
      controlElement.SetDynamicProperty("StyleMask",styleMask);
    }

    public static uint GetStyleMask(this IControlElement controlElement)
    {
    return (uint) controlElement.GetDynamicProperty("StyleMask");
    }

    public static void SetTextColor(this IControlElement controlElement, uint textColor)
    {
      controlElement.SetDynamicProperty("TextColor",textColor);
    }

    public static uint GetTextColor(this IControlElement controlElement)
    {
    return (uint) controlElement.GetDynamicProperty("TextColor");
    }

    public static void SetInfo(this IControlElement controlElement, uint info)
    {
      controlElement.SetDynamicProperty("Info",info);
    }

    public static uint GetInfo(this IControlElement controlElement)
    {
    return (uint) controlElement.GetDynamicProperty("Info");
    }

  }
}
