//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.TimeModel;

namespace zenonExtensions
{
  public static class TimeFunction
  {
    public static void SetGRP_TimeFct(this ITimeFunction timeFunction, object gRP_TimeFct)
    {
      timeFunction.SetDynamicProperty("GRP_TimeFct",gRP_TimeFct);
    }

    public static object GetGRP_TimeFct(this ITimeFunction timeFunction)
    {
    return (object) timeFunction.GetDynamicProperty("GRP_TimeFct");
    }

    public static void SetGRP_ExecutionDays(this ITimeFunction timeFunction, object gRP_ExecutionDays)
    {
      timeFunction.SetDynamicProperty("GRP_ExecutionDays",gRP_ExecutionDays);
    }

    public static object GetGRP_ExecutionDays(this ITimeFunction timeFunction)
    {
    return (object) timeFunction.GetDynamicProperty("GRP_ExecutionDays");
    }

    public static void SetGRP_Timeadj(this ITimeFunction timeFunction, object gRP_Timeadj)
    {
      timeFunction.SetDynamicProperty("GRP_Timeadj",gRP_Timeadj);
    }

    public static object GetGRP_Timeadj(this ITimeFunction timeFunction)
    {
    return (object) timeFunction.GetDynamicProperty("GRP_Timeadj");
    }

    public static void SetModifiedCnt(this ITimeFunction timeFunction, uint modifiedCnt)
    {
      timeFunction.SetDynamicProperty("ModifiedCnt",modifiedCnt);
    }

    public static uint GetModifiedCnt(this ITimeFunction timeFunction)
    {
    return (uint) timeFunction.GetDynamicProperty("ModifiedCnt");
    }

    public static void SetSoModifiedCnt(this ITimeFunction timeFunction, uint soModifiedCnt)
    {
      timeFunction.SetDynamicProperty("SoModifiedCnt",soModifiedCnt);
    }

    public static uint GetSoModifiedCnt(this ITimeFunction timeFunction)
    {
    return (uint) timeFunction.GetDynamicProperty("SoModifiedCnt");
    }

    public static void SetFunction(this ITimeFunction timeFunction, object function)
    {
      timeFunction.SetDynamicProperty("Function",function);
    }

    public static object GetFunction(this ITimeFunction timeFunction)
    {
    return (object) timeFunction.GetDynamicProperty("Function");
    }

    public static void SetSystemModelGroup(this ITimeFunction timeFunction, object systemModelGroup)
    {
      timeFunction.SetDynamicProperty("SystemModelGroup",systemModelGroup);
    }

    public static object GetSystemModelGroup(this ITimeFunction timeFunction)
    {
    return (object) timeFunction.GetDynamicProperty("SystemModelGroup");
    }

    public static void SetType(this ITimeFunction timeFunction, int type)
    {
      timeFunction.SetDynamicProperty("Type",type);
    }

    public static int GetType(this ITimeFunction timeFunction)
    {
    return (int) timeFunction.GetDynamicProperty("Type");
    }

    public static void SetExecuteDate(this ITimeFunction timeFunction, uint executeDate)
    {
      timeFunction.SetDynamicProperty("ExecuteDate",executeDate);
    }

    public static uint GetExecuteDate(this ITimeFunction timeFunction)
    {
    return (uint) timeFunction.GetDynamicProperty("ExecuteDate");
    }

    public static void SetInterval(this ITimeFunction timeFunction, uint interval)
    {
      timeFunction.SetDynamicProperty("Interval",interval);
    }

    public static uint GetInterval(this ITimeFunction timeFunction)
    {
    return (uint) timeFunction.GetDynamicProperty("Interval");
    }

    public static void SetMonthly(this ITimeFunction timeFunction, bool monthly)
    {
      timeFunction.SetDynamicProperty("Monthly",monthly);
    }

    public static bool GetMonthly(this ITimeFunction timeFunction)
    {
    return (bool) timeFunction.GetDynamicProperty("Monthly");
    }

    public static void SetYearly(this ITimeFunction timeFunction, bool yearly)
    {
      timeFunction.SetDynamicProperty("Yearly",yearly);
    }

    public static bool GetYearly(this ITimeFunction timeFunction)
    {
    return (bool) timeFunction.GetDynamicProperty("Yearly");
    }

    public static void SetMonday(this ITimeFunction timeFunction, bool monday)
    {
      timeFunction.SetDynamicProperty("Monday",monday);
    }

    public static bool GetMonday(this ITimeFunction timeFunction)
    {
    return (bool) timeFunction.GetDynamicProperty("Monday");
    }

    public static void SetTuesday(this ITimeFunction timeFunction, bool tuesday)
    {
      timeFunction.SetDynamicProperty("Tuesday",tuesday);
    }

    public static bool GetTuesday(this ITimeFunction timeFunction)
    {
    return (bool) timeFunction.GetDynamicProperty("Tuesday");
    }

    public static void SetWednesday(this ITimeFunction timeFunction, bool wednesday)
    {
      timeFunction.SetDynamicProperty("Wednesday",wednesday);
    }

    public static bool GetWednesday(this ITimeFunction timeFunction)
    {
    return (bool) timeFunction.GetDynamicProperty("Wednesday");
    }

    public static void SetThursday(this ITimeFunction timeFunction, bool thursday)
    {
      timeFunction.SetDynamicProperty("Thursday",thursday);
    }

    public static bool GetThursday(this ITimeFunction timeFunction)
    {
    return (bool) timeFunction.GetDynamicProperty("Thursday");
    }

    public static void SetFriday(this ITimeFunction timeFunction, bool friday)
    {
      timeFunction.SetDynamicProperty("Friday",friday);
    }

    public static bool GetFriday(this ITimeFunction timeFunction)
    {
    return (bool) timeFunction.GetDynamicProperty("Friday");
    }

    public static void SetSaturday(this ITimeFunction timeFunction, bool saturday)
    {
      timeFunction.SetDynamicProperty("Saturday",saturday);
    }

    public static bool GetSaturday(this ITimeFunction timeFunction)
    {
    return (bool) timeFunction.GetDynamicProperty("Saturday");
    }

    public static void SetSunday(this ITimeFunction timeFunction, bool sunday)
    {
      timeFunction.SetDynamicProperty("Sunday",sunday);
    }

    public static bool GetSunday(this ITimeFunction timeFunction)
    {
    return (bool) timeFunction.GetDynamicProperty("Sunday");
    }

  }
}
