//AUTOGENERATED FILE. Do not make any manual changes. Any changes to this file will be overwritten.

using Scada.AddIn.Contracts.UserAdministration;

namespace zenonExtensions
{
  public static class UserGroup
  {
    public static void SetGRP_General(this IUserGroup userGroup, object gRP_General)
    {
      userGroup.SetDynamicProperty("GRP_General",gRP_General);
    }

    public static object GetGRP_General(this IUserGroup userGroup)
    {
    return (object) userGroup.GetDynamicProperty("GRP_General");
    }

    public static void SetAutologout(this IUserGroup userGroup, object autologout)
    {
      userGroup.SetDynamicProperty("Autologout",autologout);
    }

    public static object GetAutologout(this IUserGroup userGroup)
    {
    return (object) userGroup.GetDynamicProperty("Autologout");
    }

    public static void SetUserGroupName(this IUserGroup userGroup, string userGroupName)
    {
      userGroup.SetDynamicProperty("UserGroupName",userGroupName);
    }

    public static string GetUserGroupName(this IUserGroup userGroup)
    {
    return (string) userGroup.GetDynamicProperty("UserGroupName");
    }

    public static void SetUserGroupLevel(this IUserGroup userGroup, string userGroupLevel)
    {
      userGroup.SetDynamicProperty("UserGroupLevel",userGroupLevel);
    }

    public static string GetUserGroupLevel(this IUserGroup userGroup)
    {
    return (string) userGroup.GetDynamicProperty("UserGroupLevel");
    }

    public static void SetUserGroupLevel0(this IUserGroup userGroup, uint userGroupLevel0)
    {
      userGroup.SetDynamicProperty("UserGroupLevel0",userGroupLevel0);
    }

    public static uint GetUserGroupLevel0(this IUserGroup userGroup)
    {
    return (uint) userGroup.GetDynamicProperty("UserGroupLevel0");
    }

    public static void SetUserGroupLevel1(this IUserGroup userGroup, uint userGroupLevel1)
    {
      userGroup.SetDynamicProperty("UserGroupLevel1",userGroupLevel1);
    }

    public static uint GetUserGroupLevel1(this IUserGroup userGroup)
    {
    return (uint) userGroup.GetDynamicProperty("UserGroupLevel1");
    }

    public static void SetUserGroupLevel2(this IUserGroup userGroup, uint userGroupLevel2)
    {
      userGroup.SetDynamicProperty("UserGroupLevel2",userGroupLevel2);
    }

    public static uint GetUserGroupLevel2(this IUserGroup userGroup)
    {
    return (uint) userGroup.GetDynamicProperty("UserGroupLevel2");
    }

    public static void SetUserGroupLevel3(this IUserGroup userGroup, uint userGroupLevel3)
    {
      userGroup.SetDynamicProperty("UserGroupLevel3",userGroupLevel3);
    }

    public static uint GetUserGroupLevel3(this IUserGroup userGroup)
    {
    return (uint) userGroup.GetDynamicProperty("UserGroupLevel3");
    }

    public static void SetGUID(this IUserGroup userGroup, string gUID)
    {
      userGroup.SetDynamicProperty("GUID",gUID);
    }

    public static string GetGUID(this IUserGroup userGroup)
    {
    return (string) userGroup.GetDynamicProperty("GUID");
    }

    public static void SetIsMsgCtrlGroup(this IUserGroup userGroup, bool isMsgCtrlGroup)
    {
      userGroup.SetDynamicProperty("IsMsgCtrlGroup",isMsgCtrlGroup);
    }

    public static bool GetIsMsgCtrlGroup(this IUserGroup userGroup)
    {
    return (bool) userGroup.GetDynamicProperty("IsMsgCtrlGroup");
    }

    public static void SetUserGroupOrder(this IUserGroup userGroup, string userGroupOrder)
    {
      userGroup.SetDynamicProperty("UserGroupOrder",userGroupOrder);
    }

    public static string GetUserGroupOrder(this IUserGroup userGroup)
    {
    return (string) userGroup.GetDynamicProperty("UserGroupOrder");
    }

    public static void SetSystemModelGroup(this IUserGroup userGroup, object systemModelGroup)
    {
      userGroup.SetDynamicProperty("SystemModelGroup",systemModelGroup);
    }

    public static object GetSystemModelGroup(this IUserGroup userGroup)
    {
    return (object) userGroup.GetDynamicProperty("SystemModelGroup");
    }

    public static void SetIsAutologoutActive(this IUserGroup userGroup, bool isAutologoutActive)
    {
      userGroup.SetDynamicProperty("IsAutologoutActive",isAutologoutActive);
    }

    public static bool GetIsAutologoutActive(this IUserGroup userGroup)
    {
    return (bool) userGroup.GetDynamicProperty("IsAutologoutActive");
    }

    public static void SetAutologoutMinutes(this IUserGroup userGroup, ushort autologoutMinutes)
    {
      userGroup.SetDynamicProperty("AutologoutMinutes",autologoutMinutes);
    }

    public static ushort GetAutologoutMinutes(this IUserGroup userGroup)
    {
    return (ushort) userGroup.GetDynamicProperty("AutologoutMinutes");
    }

  }
}
